package com.github.beowolve.snapfx.model;

import javafx.beans.property.*;
import javafx.scene.Node;

import java.util.UUID;

/**
 * Wrapper class for a dockable JavaFX node.
 * Encapsulates a JavaFX Node with metadata such as title and ID.
 *
 * <p>Uses two types of IDs:</p>
 * <ul>
 *   <li><b>dockNodeId</b>: Type-based identifier used by the factory to create nodes (e.g., "editor", "console")</li>
 *   <li><b>layoutId</b>: Unique identifier for this specific instance in the layout (managed by framework)</li>
 * </ul>
 */
public class DockNode implements DockElement {
    private final String dockNodeId; // Type-based ID for factory
    private String layoutId; // Unique ID for this instance in layout
    private final StringProperty title;
    private final ObjectProperty<Node> content;
    private final ObjectProperty<Node> icon;
    private final BooleanProperty closeable;
    private DockContainer parent;

    // Store last known position for restore
    private DockElement lastKnownTarget;
    private DockPosition lastKnownPosition;

    /**
     * Creates a DockNode with an auto-generated UUID as both dockNodeId and layoutId.
     * Note: UUIDs change between sessions, making persistence unreliable.
     * For proper save/load support, use the constructor with a custom dockNodeId.
     */
    public DockNode(Node content, String title) {
        this(UUID.randomUUID().toString(), content, title);
    }

    /**
     * Creates a DockNode with a custom dockNodeId.
     * Use this constructor for nodes that need to be persisted across sessions.
     * The layoutId will be auto-generated by the framework when added to the layout.
     *
     * @param dockNodeId Type-based identifier for this node (e.g., "editor", "console", "projectExplorer")
     * @param content The JavaFX node to display
     * @param title The title shown in headers and tabs
     */
    public DockNode(String dockNodeId, Node content, String title) {
        this.dockNodeId = dockNodeId;
        this.layoutId = null; // Will be set by framework when added to layout
        this.content = new SimpleObjectProperty<>(content);
        this.title = new SimpleStringProperty(title);
        this.icon = new SimpleObjectProperty<>(null);
        this.closeable = new SimpleBooleanProperty(true);
    }

    // Getters

    /**
     * Returns the unique layout ID for this node instance.
     * This ID is used for positioning in the layout structure.
     * It is automatically generated by the framework when the node is added to a layout.
     */
    public String getId() {
        return layoutId;
    }

    /**
     * Returns the type-based dockNodeId used by the factory.
     * This ID identifies the type of node (e.g., "editor", "console").
     */
    public String getDockNodeId() {
        return dockNodeId;
    }

    /**
     * Sets the unique layout ID for this node instance.
     * This is called by the framework when the node is added to a layout.
     */
    public void setLayoutId(String layoutId) {
        this.layoutId = layoutId;
    }

    public String getTitle() {
        return title.get();
    }

    public StringProperty titleProperty() {
        return title;
    }

    public void setTitle(String title) {
        this.title.set(title);
    }

    public Node getContent() {
        return content.get();
    }

    public ObjectProperty<Node> contentProperty() {
        return content;
    }

    public void setContent(Node content) {
        this.content.set(content);
    }

    public Node getIcon() {
        return icon.get();
    }

    public ObjectProperty<Node> iconProperty() {
        return icon;
    }

    public void setIcon(Node icon) {
        this.icon.set(icon);
    }

    public boolean isCloseable() {
        return closeable.get();
    }

    public BooleanProperty closeableProperty() {
        return closeable;
    }

    public void setCloseable(boolean closeable) {
        this.closeable.set(closeable);
    }

    @Override
    public DockContainer getParent() {
        return parent;
    }

    @Override
    public void setParent(DockContainer parent) {
        this.parent = parent;
    }

    public DockElement getLastKnownTarget() {
        return lastKnownTarget;
    }

    public void setLastKnownTarget(DockElement lastKnownTarget) {
        this.lastKnownTarget = lastKnownTarget;
    }

    public DockPosition getLastKnownPosition() {
        return lastKnownPosition;
    }

    public void setLastKnownPosition(DockPosition lastKnownPosition) {
        this.lastKnownPosition = lastKnownPosition;
    }

    @Override
    public String toString() {
        return "DockNode{layoutId='" + getId() + "', dockNodeId='" + dockNodeId + "', title='" + title.get() + "'}";
    }
}
